import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
// eslint-disable-next-line no-unused-vars
import { motion, AnimatePresence } from 'framer-motion';
import { Loader2, ArrowRight, BookOpen, Clock, Tag } from 'lucide-react';
import CardNav from '../components/CardNav';

export default function Blog() {
    const navigate = useNavigate();
    const [blogs, setBlogs] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        const fetchBlogs = async () => {
            try {
                const baseUrl = window.location.hostname === 'localhost' ? 'http://localhost:3000' : '';
                const response = await fetch(`${baseUrl}/api/nest/blog`);
                if (!response.ok) throw new Error('Failed to fetch AI blogs');
                const data = await response.json();
                setBlogs(data);
            } catch (err) {
                console.error(err);
                setError('Could not load latest articles. The AI editor might be resting.');
            } finally {
                setLoading(false);
            }
        };

        fetchBlogs();
    }, []);

    return (
        <div className="min-h-screen bg-zinc-950 text-white font-sans selection:bg-cyan-500/30 pb-20">
            <CardNav />
            <main className="pt-32 px-6 max-w-7xl mx-auto">
                <div className="mb-12">
                    <motion.h1
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="text-4xl md:text-5xl lg:text-6xl font-black capitalize tracking-tight mb-4 flex items-center gap-4"
                    >
                        <BookOpen className="w-10 h-10 text-cyan-500" />
                        The Daily Rep
                    </motion.h1>
                    <motion.p
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.1 }}
                        className="text-zinc-400 text-lg max-w-2xl"
                    >
                        Fresh insights on sports science, training methodology, and recovery generated by Google Gemini AI.
                    </motion.p>
                </div>

                {loading ? (
                    <div className="flex flex-col items-center justify-center py-32 text-cyan-500 gap-4">
                        <Loader2 className="w-12 h-12 animate-spin" />
                        <span className="text-xl font-bold animate-pulse">Consulting the AI Editor...</span>
                    </div>
                ) : error ? (
                    <div className="bg-red-500/10 border border-red-500/20 text-red-400 p-6 rounded-2xl text-center">
                        {error}
                    </div>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                        <AnimatePresence>
                            {blogs.map((blog, idx) => (
                                <motion.div
                                    key={blog.id}
                                    initial={{ opacity: 0, scale: 0.95, y: 20 }}
                                    animate={{ opacity: 1, scale: 1, y: 0 }}
                                    transition={{ delay: idx * 0.1 }}
                                    onClick={() => navigate(`/blog/${blog.id}`)}
                                    className="group flex flex-col bg-zinc-900/40 border border-zinc-800/80 hover:border-cyan-500/50 rounded-3xl p-8 cursor-pointer transition-all hover:bg-zinc-800/50 shadow-xl"
                                >
                                    <div className="flex items-center gap-3 mb-4 text-xs font-bold text-zinc-500 uppercase tracking-widest">
                                        <span className="text-cyan-400">{blog.date}</span>
                                        <span className="w-1 h-1 rounded-full bg-zinc-700"></span>
                                        <span className="flex items-center gap-1"><Clock className="w-3 h-3" /> {blog.readTime}</span>
                                    </div>

                                    <h2 className="text-2xl font-black mb-4 leading-tight group-hover:text-cyan-300 transition-colors">
                                        {blog.title}
                                    </h2>

                                    <p className="text-zinc-400 leading-relaxed mb-6 flex-1">
                                        {blog.excerpt}
                                    </p>

                                    <div className="flex flex-wrap gap-2 mt-auto mb-6">
                                        {blog.tags?.slice(0, 3).map(tag => (
                                            <span key={tag} className="flex items-center gap-1 text-xs font-semibold bg-zinc-950 px-3 py-1.5 rounded-lg border border-zinc-800 text-zinc-300">
                                                <Tag className="w-3 h-3 text-cyan-500" /> {tag}
                                            </span>
                                        ))}
                                    </div>

                                    <div className="flex items-center justify-between text-zinc-500 font-bold text-sm uppercase tracking-wide group-hover:text-cyan-400 transition-colors border-t border-zinc-800 pt-6">
                                        <span>Read Article</span>
                                        <ArrowRight className="w-5 h-5 group-hover:-rotate-45 transition-transform" />
                                    </div>
                                </motion.div>
                            ))}
                        </AnimatePresence>
                    </div>
                )}
            </main>
        </div>
    );
}
